version: 0.2

phases:
  install:
    commands:
      - git config --global credential.helper '!aws codecommit credential-helper $@'
      - git config --global credential.UseHttpPath true
  pre_build:
    commands:
      - echo moving stuff
      - ls -la
      - pwd
      - cd nodejs/blue-button-generate-el8
      - mkdir nodejs
      - cp package.json nodejs
      - cd nodejs
      - ls -la
      - pwd
      - npm install
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Node.js code
      - cd ..
      - ls -la
      - pwd
      - zip -r blue-button-generate-el8.zip nodejs
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - nodejs/blue-button-generate-el8/blue-button-generate-el8.zip
